steps:
  #push the source repo.
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/akshay-jedhe/SpringBootProjects.git']
  #build the target image.
- name: 'gcr.io/cloud-builders/docker'
  dir: './SpringBootProjects/docker/'
  args: ['build','-t','gcr.io/${PROJECT_ID}/myapp:${BUILD_ID}','.']
  #push the target image to the gcr
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${PROJECT_ID}/myapp:${BUILD_ID}']
  #deploy the target image to the gke.
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set','image','deployment/myapp-deployment','myapp=myapp:${BUILD_ID}']
  
