apiVersion: apps/v1
kind: Deployment
metadata:
   name: myapp-deployment
spec:
   replicas: 3
   selector:
      matchLabels:
         app-name: my-app
   template:
      metadata:
         labels:
            app-name: my-app
      spec:
         containers:
         - name: myapp-ctn
           image: akshayjedhe/demoapp
           ports:
           - containerPort: 30001

