apiVersion: skaffold/v1
kind: Config
metadata:
   name: my-springboot-project
build:
   artifacts:
   - image: akshayjedhe/demoapp
     jib: {}
   local: {}
deploy:
   kubectl:
      manifests:
      - myapp-*
