apiVersion: v1
kind: Service
metadata:
   name: myapp-service
spec:
   selector:
      app-name: my-app
   type: NodePort
   ports:
   - name: myapp-port
     targetPort: 30001
     port: 30001
     nodePort: 30001
     protocol: "TCP"

